# Generated by Django 3.2.12 on 2022-05-02 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_alter_house_postal_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('read_project', 'Read Project'),)},
        ),
    ]
